name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Update Packagist
        run: |
          curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=palkan&apiToken=${{ secrets.PACKAGIST_API_TOKEN }}' -d'{"repository":{"url":"https://packagist.org/packages/anycable/laravel-broadcaster"}}'
